export enum ETableNames {
    atividades = 'atividades',
    clientes = 'clientes',
    empresas = 'empresas',
    fornecedores = 'fornecedores',
    grupos = 'grupos',
    modelos = 'modelos',
    ncm = 'ncm',
    produtos = 'produtos',
    subTipos = 'subTipos',
    tipos = 'tipos',
    transportadoras = 'transportadoras',
    tributacoes = 'tributacoes',
    usuarios = 'usuarios',
    vendedores = 'vendedores',
    pedidosVendas = 'pedidosVendas',
    pedidosVendasProdutos = 'pedidosVendasProdutos',
    pedidosVendasTotais = 'pedidosVendasTotais',
    pedidosVendasPagamentos = 'pedidosVendasPagamentos',
    pedidosVendasTransportadoras = 'pedidosVendasTransportadoras',
    pedidosVendasMensagens = 'pedidosVendasMensagens'
}